package com.reborn.shinobicore.ko.injury;

import org.bukkit.configuration.ConfigurationSection;

import java.util.UUID;

/**
 * A single wound on a body part.
 *
 * <p>Injuries are mutable through:
 * <ul>
 *   <li>{@link #setSeverity(Severity)} — stepped down by a successful
 *       {@code /soigner} application, or stepped UP when the bearer
 *       goes KO (every fresh KO worsens every pre-existing wound by
 *       one tier).</li>
 *   <li>{@link #setNextHealableMillis(long)} — wall-clock millis at
 *       which {@code /soigner} can act on this injury again. Set
 *       after a successful heal based on the severity that was just
 *       healed FROM (URGENT 3h, IMPORTANT 1h30, MOYEN 30min, FAIBLE
 *       no cooldown). A KO that worsens the injury resets this back
 *       to 0 — the medic can immediately treat the new severity.</li>
 *   <li>{@link #setLastTick(long)} — kept for legacy callers; not
 *       used by the cooldown logic.</li>
 * </ul>
 *
 * <p>Injuries persist on the bearer (character or dummy) until a
 * {@code /soigner} application clears them. {@code /sc heal},
 * {@code /dummy heal}, the Tuer flow, KO auto-wake — none of those
 * touch the injury list. Only {@code /soigner} downgrades and clears.
 *
 * <p>The injury is keyed by a stable {@link #id()} so the silhouette
 * GUI can reference a specific wound without index races.
 */
public final class Injury {

    private final UUID         id;
    private final BodyPart     bodyPart;
    private final InjuryType   type;
    private final DamageOrigin origin;
    private       Severity     severity;
    private final long         createdAtMillis;
    private       long         lastTick;
    private       long         nextHealableMillis;
    /** Hidden injuries are filtered out of every silhouette / list /
     *  count. Set when an Os cassé is generated by an Hématome merge
     *  to IMPORTANT or URGENT — the fracture stays invisible until
     *  the medic heals the parent bruise. */
    private       boolean      hidden;

    public Injury(UUID id, BodyPart bodyPart, InjuryType type,
                  DamageOrigin origin, Severity severity,
                  long createdAtMillis, long lastTick,
                  long nextHealableMillis, boolean hidden) {
        this.id                 = id;
        this.bodyPart           = bodyPart;
        this.type               = type;
        this.origin             = origin;
        this.severity           = severity;
        this.createdAtMillis    = createdAtMillis;
        this.lastTick           = lastTick;
        this.nextHealableMillis = nextHealableMillis;
        this.hidden             = hidden;
    }

    public static Injury create(BodyPart bodyPart, InjuryType type,
                                DamageOrigin origin, Severity severity) {
        long now = System.currentTimeMillis();
        return new Injury(UUID.randomUUID(),
                bodyPart, type, origin, severity, now, now, 0L, false);
    }

    public UUID         id()                  { return id; }
    public BodyPart     bodyPart()            { return bodyPart; }
    public InjuryType   type()                { return type; }
    public DamageOrigin origin()              { return origin; }
    public Severity     severity()            { return severity; }
    public long         createdAtMillis()     { return createdAtMillis; }
    public long         lastTick()            { return lastTick; }
    public long         nextHealableMillis()  { return nextHealableMillis; }
    public boolean      hidden()              { return hidden; }

    public void setSeverity(Severity s)              { this.severity = s; }
    public void setLastTick(long t)                  { this.lastTick = t; }
    public void setNextHealableMillis(long t)        { this.nextHealableMillis = t; }
    public void setHidden(boolean v)                 { this.hidden = v; }

    /** True iff this injury can be acted on by {@code /soigner} right
     *  now (no cooldown active). */
    public boolean isHealable() {
        return System.currentTimeMillis() >= nextHealableMillis;
    }

    /** Remaining cooldown in millis, clamped to 0. */
    public long cooldownRemainingMillis() {
        return Math.max(0L, nextHealableMillis - System.currentTimeMillis());
    }

    /* ------------------------------------------------------ YAML I/O */

    public void writeTo(ConfigurationSection s) {
        s.set("id",        id.toString());
        s.set("body",      bodyPart.name());
        s.set("type",      type.name());
        s.set("origin",    origin.name());
        s.set("severity",  severity.name());
        s.set("createdAt", createdAtMillis);
        s.set("lastTick",  lastTick);
        // Only persist the cooldown when it's in the future — saves a
        // few bytes per injury and keeps old YAMLs unaffected.
        s.set("nextHealable", nextHealableMillis > 0 ? nextHealableMillis : null);
        s.set("hidden",       hidden ? true : null);
    }

    public static Injury readFrom(ConfigurationSection s) {
        try {
            BodyPart body = BodyPart.parseLenient(
                    s.getString("body", BodyPart.BUSTE_GAUCHE.name()));
            if (body == null) body = BodyPart.BUSTE_GAUCHE;
            return new Injury(
                    UUID.fromString(s.getString("id", UUID.randomUUID().toString())),
                    body,
                    InjuryType.valueOf(s.getString("type", InjuryType.HEMATOME.name())),
                    DamageOrigin.valueOf(s.getString("origin", DamageOrigin.AUTRE.name())),
                    Severity.valueOf(s.getString("severity", Severity.FAIBLE.name())),
                    s.getLong("createdAt", System.currentTimeMillis()),
                    s.getLong("lastTick",  System.currentTimeMillis()),
                    s.getLong("nextHealable", 0L),
                    s.getBoolean("hidden", false));
        } catch (IllegalArgumentException ex) {
            return null; // skip malformed
        }
    }
}
